Repository swimos/swimos-docs, pull requests merged in 2023-08, with the labels that each got.

#64 Issue 60/cli how to
  .gitignore
  _config.yml
  _includes/bar.html
  _includes/header.html
  src/_guides/cli.md
Labels: documentation

#76 Cleanup extra bold tags
  src/_reference/forms.md
Labels: bug

#71 Fix syntax for example in auth-policy.md
  src/_reference/auth-policy.md
Labels: bug

#68 chore: Add Google Analytics 4. Closes #34
  _includes/google-analytics.html
  _layouts/default.html
  _layouts/page.html
Labels: documentation, housekeeping

#65 Added 'Time Series' How To guide
  _config.yml
  src/_guides/time-series.md
Labels: documentation

#83 docs: Add conventions and PR process to contribution guide. Closes #74
  src/_meta/contribute.md
Labels: documentation, enhancement

#90 fix: Make G4 render
  _includes/head.html
Labels: bug
