Repository swimos/swimos-docs, pull requests merged in 2023-10, with the labels that each got.

#112 Update linkchecker.rb. Closes #2
  _plugins/linkchecker.rb
Labels: bug

#116 Re-added stateful-entities page back to SwimOS as Web Agents
  src/_reference/web-agents.md
Labels: documentation

#119 Add feedback widget to docs pages. Closes #118
  _layouts/page.html
Labels: documentation, enhancement

#124 Added JMS ingestion guide
  _config.yml
  src/_guides/jms-ingestion.md
Labels: documentation

#122 Added MongoDB ingestion guide
  _config.yml
  src/_guides/mongodb-ingestion.md
Labels: documentation
